### ISSUE TITLE
media queries are ignored in full mode

### ISSUE THREAD

**Issue by lmestel** [Dschungelabenteuer/custom-property-extract#1]
Hi,

this package is very usefull, but unfortunately there's a bug in the full mode output:

The following CSS
```css
:root {
  --color-primary: #ff017d;
}

[data-lang="us"] {
  --amount-suffix-content: "$";
}

@media screen and (min-width: 960px) {
  :root {
    --color-primary: blue;
  }
}

```

results in this output (full mode):

```js
{
  '--color-primary': [
    { selector: ':root ', value: '#ff017d' },
    { selector: '[data-lang="us"]:root ', value: 'blue' } // <-- !!
  ],
  '--amount-suffix-content': [ 
    { selector: '[data-lang="us"] ', value: '"$"' } 
  ]
}
```

`{ selector: '[data-lang="us"]:root ', value: 'blue' }` for `--color-primary` is wrong. 
It seems the media query is ignored and the selector (`:root`) is merged with the last one (`[data-lang="us"]`).

What do you think about an additional property - e.g. `media` - beside `selector`, `value` (and `name`) to map the media query?
